In [1]:
import nashpy as nash
import numpy as np

In [3]:
game_matrix = np.array([[2.75, 0.5,  2.4,  0.6 ],
 [4.,   1.3,  2.7,  1.5 ],
 [2.9,  1.2,  2.15, 2.1 ],
 [4.6,  2.,   2.1,  1.65]])

In [5]:
list(nash.Game(game_matrix, game_matrix.transpose()).support_enumeration())

C:\Users\sophi\Anaconda3\lib\site-packages\nashpy\algorithms\support_enumeration.py:196: RuntimeWarning: 
An even number of (0) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


[]

In [6]:
list(nash.Game(game_matrix, game_matrix.transpose()).vertex_enumeration())

[(array([-3.96146399e-17,  2.39740821e-01,  3.75809935e-01,  3.84449244e-01]),
  array([-3.96146399e-17,  2.39740821e-01,  3.75809935e-01,  3.84449244e-01]))]

In [7]:
list(nash.Game(game_matrix, game_matrix.transpose()).lemke_howson_enumeration())

[(array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924]))]

In [2]:
matrix2 = np.array([[3.,         1.82736777, 0.9928776 ],
 [1.00928174, 2.99071312, 0.75125343],
 [1.02848961, 1.99498629, 1.        ]])


In [3]:
list(nash.Game(matrix2, matrix2.transpose()).support_enumeration())

[(array([1., 0., 0.]), array([1., 0., 0.])),
 (array([0., 1., 0.]), array([0., 1., 0.])),
 (array([0., 0., 1.]), array([0., 0., 1.])),
 (array([0.36884017, 0.63115983, 0.        ]),
  array([0.36884017, 0.63115983, 0.        ])),
 (array([3.59965732e-03, 3.33804640e-17, 9.96400343e-01]),
  array([3.59965732e-03, 3.33804640e-17, 9.96400343e-01])),
 (array([0.        , 0.19988099, 0.80011901]),
  array([0.        , 0.19988099, 0.80011901])),
 (array([0.01952088, 0.19628043, 0.78419869]),
  array([0.01952088, 0.19628043, 0.78419869]))]

In [4]:
list(nash.Game(matrix2, matrix2.transpose()).vertex_enumeration())

[(array([ 1.00000000e+00, -4.16333634e-17, -4.16333634e-17]),
  array([ 1.00000000e+00, -4.16333634e-17, -4.16333634e-17])),
 (array([-4.15044821e-17,  1.00000000e+00,  0.00000000e+00]),
  array([-4.15044821e-17,  1.00000000e+00,  0.00000000e+00])),
 (array([3.68840167e-01, 6.31159833e-01, 3.13621578e-17]),
  array([3.68840167e-01, 6.31159833e-01, 3.13621578e-17])),
 (array([-1.38777878e-17, -4.16333634e-17,  1.00000000e+00]),
  array([-1.38777878e-17, -4.16333634e-17,  1.00000000e+00])),
 (array([3.59965732e-03, 1.38792110e-17, 9.96400343e-01]),
  array([3.59965732e-03, 1.38792110e-17, 9.96400343e-01])),
 (array([0.        , 0.19988099, 0.80011901]),
  array([0.        , 0.19988099, 0.80011901])),
 (array([0.01952088, 0.19628043, 0.78419869]),
  array([0.01952088, 0.19628043, 0.78419869]))]

In [5]:
list(nash.Game(matrix2, matrix2.transpose()).lemke_howson_enumeration())

[(array([1., 0., 0.]), array([1., 0., 0.])),
 (array([0., 1., 0.]), array([0., 1., 0.])),
 (array([0., 0., 1.]), array([0., 0., 1.])),
 (array([1., 0., 0.]), array([1., 0., 0.])),
 (array([0., 1., 0.]), array([0., 1., 0.])),
 (array([0., 0., 1.]), array([0., 0., 1.]))]