In [1]:
import nashpy as nash
import numpy as np

In [3]:
game_matrix = np.array([[2.75, 0.5,  2.4,  0.6 ],
 [4.,   1.3,  2.7,  1.5 ],
 [2.9,  1.2,  2.15, 2.1 ],
 [4.6,  2.,   2.1,  1.65]])

In [5]:
list(nash.Game(game_matrix, game_matrix.transpose()).support_enumeration())

C:\Users\sophi\Anaconda3\lib\site-packages\nashpy\algorithms\support_enumeration.py:196: RuntimeWarning: 
An even number of (0) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


[]

In [6]:
list(nash.Game(game_matrix, game_matrix.transpose()).vertex_enumeration())

[(array([-3.96146399e-17,  2.39740821e-01,  3.75809935e-01,  3.84449244e-01]),
  array([-3.96146399e-17,  2.39740821e-01,  3.75809935e-01,  3.84449244e-01]))]

In [7]:
list(nash.Game(game_matrix, game_matrix.transpose()).lemke_howson_enumeration())

[(array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924])),
 (array([0.        , 0.23974082, 0.37580994, 0.38444924]),
  array([0.        , 0.23974082, 0.37580994, 0.38444924]))]